"""Project-owned configuration for invisible-watermark regeneration profiles.

Two profiles remain: ``qwen-zimage`` (the default on CUDA) and ``sdxl-zimage``, which
is the only one that can also run on Apple Silicon (MPS). The older ``controlnet``,
``sdxl``, ``qwen`` and ``default`` profiles were removed rather than kept as a CPU
path, because none of them matched the two-stage recipe's face preservation and keeping
them implied a quality this library no longer offers. Removing invisible watermarks
therefore still needs a GPU -- CUDA or MPS; the visible-mark registry and every
identify path run anywhere.

The device split is a property of the model stacks, not a policy choice:

- ``qwen-zimage`` streams its weights as ``torch.float8_e4m3fn`` and computes in
  bfloat16 under DiffSynth's VRAM manager. Metal has no float8 tensor type at all
  (``RuntimeError: Undefined type Float8_e4m3fn``), so that stack cannot be loaded on
  MPS, let alone offloaded by it.
- ``sdxl-zimage``'s global stage is plain Diffusers -- SDXL + a Canny ControlNet +
  the four-step Lightning LoRA in fp16 -- which is exactly the workload MPS supports.
- The Z-Image face stage is DiffSynth again and carries the same float8 storage, so
  it stays CUDA-only. On MPS the profile therefore runs its global stage alone. That
  is a documented degradation, not a silent one: :func:`plan_profile` reports it and
  the CLI prints it.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from pathlib import Path

# SDXL base is no longer a profile of its own, but it is still the global stage of
# sdxl-zimage, so the checkpoint id stays. Named for what it is rather than
# ``DEFAULT_MODEL_ID``: there is no user-selectable model any more, so "default"
# implied an override that both profiles reject.
SDXL_MODEL_ID = "stabilityai/stable-diffusion-xl-base-1.0"
CONTROLNET_CANNY_MODEL = "xinsir/controlnet-canny-sdxl-1.0"

QWEN_ZIMAGE_PROFILE = "qwen-zimage"
SDXL_ZIMAGE_PROFILE = "sdxl-zimage"
DEFAULT_PROFILE = QWEN_ZIMAGE_PROFILE
PROFILE_CHOICES = (QWEN_ZIMAGE_PROFILE, SDXL_ZIMAGE_PROFILE)

CUDA_DEVICE = "cuda"
MPS_DEVICE = "mps"
CPU_DEVICE = "cpu"

# Which devices each profile's global stage can execute on. Read by the remover's
# precondition, by the CLI's availability gate, and by the profile default, so a
# device that a stack cannot load is refused once rather than at four call sites.
PROFILE_DEVICES: dict[str, tuple[str, ...]] = {
    QWEN_ZIMAGE_PROFILE: (CUDA_DEVICE,),
    SDXL_ZIMAGE_PROFILE: (CUDA_DEVICE, MPS_DEVICE),
}

# A face stage runs on both GPUs, but not the same one. Z-Image is DiffSynth with
# float8 storage, so Metal cannot load it; there the crops are regenerated by the SDXL
# stack the global pass already has resident, which costs no additional model.
FACE_STAGE_DEVICES = (CUDA_DEVICE, MPS_DEVICE)
ZIMAGE_FACE_DEVICES = (CUDA_DEVICE,)

# The SDXL face stage's own constants, all three measured on an M5 rather than carried
# over from the Z-Image stage they replace:
#
# - the crop cap. Upstream scales a crop toward a 768px face guide and caps it at
#   1024. For a 120px face that is memory spent on detail the face does not carry, and
#   on a 16 GiB Mac it is the difference between 1.5 s/step and 19 s/step.
# - the strength floor. At the 0.025 the inherited policy resolves to for a photo of
#   small faces, three of four crops came back as all-zero rectangles while 0.05
#   produced 30.5 dB PSNR at identical crop sizes -- so strength moves this, and the
#   floor stays. It is NOT the numerical limit it first looked like, though: the same
#   silent-zero failure was later reproduced at 0.05 by nothing more than freeing 1.5 GiB
#   of unrelated memory, which makes strength one trigger of a Metal fp16 instability
#   rather than its cause. The floor is a mitigation; the guard in `_run_faces` is the
#   protection.
# - the step count, which is the Z-Image stage's own and needs no change: a crop is
#   small enough that more steps cost little, and 8 measured well.
SDXL_FACE_CROP_CAP = 640
SDXL_FACE_STRENGTH_FLOOR = 0.05
SDXL_FACE_STEPS = 8

# The modules a real removal run needs, and the extra that installs them. Both live
# here, in the only profile module that imports nothing heavy, because the CLI's
# availability gate and the remover's own precondition must agree: when they drifted,
# the CLI passed on a torch+diffusers environment and the run then died at the
# DiffSynth face stage, telling the user to install an extra that does not contain it.
#
# The requirement is per-device for the same reason it is one constant on CUDA: what
# the run actually loads. A CUDA run reaches the face stage, so diffsynth is part of
# the answer; an MPS run cannot reach it on any input, so requiring it there would
# refuse to start a run that works and name an extra that does not install on macOS.
BASE_REMOVAL_MODULES = ("torch", "diffusers")
FACE_STAGE_MODULES = ("diffsynth",)
REMOVAL_MODULES = BASE_REMOVAL_MODULES + FACE_STAGE_MODULES
# Shell-quoted, because this string is printed as a command the user copy-pastes.
# Bare brackets are a glob in zsh (the macOS default shell): an unquoted
# ``pip install pagedmark[qwen-zimage]`` dies with "no matches found"
# before pip ever runs -- another install hint that does not install.
INVISIBLE_EXTRA = "'pagedmark[qwen-zimage]'"
# The Apple Silicon path installs the Diffusers stack without DiffSynth: the face
# stage it carries cannot run on Metal, and `qwen-zimage` would download a model
# stack no MPS device can load.
INVISIBLE_EXTRA_MPS = "'pagedmark[diffusion]'"

# qwen-zimage's output already matches the input's detail level, so polishing it is a
# no-op at best. sdxl-zimage's global pass leaves the softer output the polish exists
# for. This is per-profile data, not a CLI concern: the flag defaults to None so that
# "the user did not choose" stays a value rather than an inference from Click state.
PROFILE_ADAPTIVE_POLISH = {QWEN_ZIMAGE_PROFILE: False, SDXL_ZIMAGE_PROFILE: True}

SDXL_LIGHTNING_MODEL_ID = "ByteDance/SDXL-Lightning"
SDXL_LIGHTNING_PATTERN = "sdxl_lightning_4step_lora.safetensors"

# The four-step distillation is used where its operating point was measured, and
# nowhere else. It is distilled for four timesteps spanning the FULL noise range;
# this profile instead runs the TAIL of a long schedule (strength 0.15 executes the
# last four of 27), which is off-distribution for it. Where the input then offers no
# conditioning -- a flat, dark region carries no Canny edges -- the distilled model
# invents texture to fill it, measured on an M5 as 2.10x the source's 4-16 px luma
# energy and 1.73x its chroma energy inside the flat dark regions of a night photo.
#
# Asking the LoRA for more steps makes it worse (8 steps: 1.80x, 16 steps: 1.84x),
# which is what identifies the distillation rather than the step count as the cause.
# The undistilled base model at 16 effective steps drops the same measurement to
# 1.19x and RAISES fidelity (PSNR 29.25 against 28.54), at ~3x the wall time.
#
# CUDA keeps the LoRA: its verdicts were recorded with it, and re-deciding an oracle
# result from an artifact measurement on one image would be trading evidence for a
# preference. MPS has no such record to preserve -- it is a new path -- so it takes
# the sampling that measured better. Full record: docs/module-internals.md.
SDXL_LIGHTNING_DEVICES = (CUDA_DEVICE,)
SDXL_UNDISTILLED_GLOBAL_STEPS = 16

# How much of the device the weights want, measured on an M5 with the text encoders
# released -- an experiment that is no longer taken (see the note below), so treat the
# resident figure as the floor rather than the exact number:
#
# - resident: 7.70 GiB peak while running a 0.44 MP frame, 7.1 s.
# - sequentially offloaded to the CPU: 0.28 GiB peak for the same frame, 24.1 s.
#
# The second number is what makes a small Mac usable at all: a 16 GiB machine reports an
# 11.84 GiB working set, an 8 GiB one about 5.3 GiB, and the resident stack does not fit
# the latter with or without the encoder saving. Offloading trades 3.4x the wall time for
# a peak that fits anything.
SDXL_RESIDENT_STACK_GIB = 7.7
SDXL_OFFLOADED_STACK_GIB = 0.3
# Below this there is nothing left to trade: the offloaded path still needs room for one
# module plus the frame's activations, and a budget this small means the device is not
# the tool's problem to solve.
SDXL_MIN_BUDGET_GIB = 2.0


@dataclass(frozen=True)
class ResidencyPlan:
    """Where the SDXL weights live for this run."""

    offload: bool
    # Set when the plan is not the fast one, so the CLI can say why a run is slow before
    # the user waits through it.
    note: str | None = None


def sdxl_residency_plan(memory_gib: float) -> ResidencyPlan:
    """Choose between resident weights and sequential CPU offload from the budget.

    Decided at load time from the device budget alone. Per-frame activation pressure is
    a separate question, handled by `vae_tiling_needed` and `fits_in_one_pass`, because
    it depends on an image this function has not seen.

    An unreadable budget (0.0) offloads: it is the plan that runs everywhere, and a wrong
    guess costs time rather than an hour of paging.
    """
    if memory_gib <= 0.0:
        return ResidencyPlan(
            offload=True,
            note=(
                "This device's memory budget could not be read, so the weights stream from "
                "the CPU. Slower, but it runs anywhere."
            ),
        )
    if memory_gib < SDXL_MIN_BUDGET_GIB:
        raise ValueError(
            f"This device reports a {memory_gib:.1f} GiB working set, and the smallest workable "
            f"configuration needs about {SDXL_MIN_BUDGET_GIB:.0f} GiB. Visible-mark removal, "
            "metadata stripping and every identify command still run here."
        )
    if memory_gib >= SDXL_RESIDENT_STACK_GIB + 1.5:
        return ResidencyPlan(offload=False)
    return ResidencyPlan(
        offload=True,
        note=(
            f"{memory_gib:.1f} GiB is not enough to hold the {SDXL_RESIDENT_STACK_GIB:.1f} GiB stack, "
            "so the weights stream from the CPU one module at a time. Expect roughly three times "
            "the wall time for the same output."
        ),
    )


# Encoding the two fixed prompts once and releasing the text encoders frees a measured
# 1.52 GiB of the 8.79 GiB the loaded stack holds, and it is NOT done here. It was, and
# it produced all-zero face crops: with the encoders resident every crop of a four-face
# photo came back correct, and with them released the two 512-px-wide crops came back as
# black rectangles, deterministically, at the same seed. The embeddings themselves are
# not the problem -- CPU fp16, MPS fp16 and fp32 encodings of that prompt agree to 0.0009
# on tensors with a standard deviation of 3.06, and the same crop generated in isolation
# is correct either way. What changes is the allocation pattern the crops run into after
# the global pass, and fp16 sampling on Metal answers a bad one with silent zeros.
#
# 1.5 GiB is not worth a black rectangle over someone's face, and the small-memory path
# does not need it: sequential offload already brings the peak to 0.28 GiB. The guard in
# `_run_faces` now catches an empty crop whatever produces it.


def sdxl_lightning_enabled(device: str) -> bool:
    """Whether the SDXL global stage fuses the four-step distillation LoRA."""
    return device.casefold() in SDXL_LIGHTNING_DEVICES


def sdxl_global_steps(device: str, distilled_steps: int) -> int:
    """Effective denoising steps for the SDXL global stage on this device.

    ``distilled_steps`` is the profile's own step count, which the distilled schedule
    is built around; a device that does not run the distillation needs the longer
    undistilled one instead.
    """
    return distilled_steps if sdxl_lightning_enabled(device) else SDXL_UNDISTILLED_GLOBAL_STEPS


# Both profiles are certified at a fixed seed because SynthID removal near the
# strength floor is seed-dependent. The step count and CFG are not settable at all --
# each stage owns them (``GLOBAL_STEPS`` / ``FACE_STEPS`` in qwen_zimage_pipeline).
PROFILE_SEED = 0

# sdxl-zimage runs the qwen-zimage recipe on an SDXL global stage, and strength is
# architecture-bound: at Qwen's 0.154 an SDXL global pass leaves SynthID on a native
# 2816x1536 Gemini original, while 0.20, 0.25 and 0.30 all read clean in the Gemini
# app. 0.25 keeps a rung of margin over that boundary, which the historical SDXL
# certification argues for -- it recorded 0.20 as DETECTED against Gemini on an
# older SDXL pipeline. OpenAI is the easier oracle: the profile already cleared
# openai.com/verify at 0.1102, so 0.15 sits above what was verified rather than on
# it. Unknown follows Gemini, the stricter of the two.
#
# Unlike qwen-zimage this is a flat vendor policy rather than a resolution curve,
# because flat values are what was measured. Every verdict above comes from a fixed
# strength at one size; no size dependence has been established for this stage.
SDXL_ZIMAGE_OPENAI_STRENGTH = 0.15
SDXL_ZIMAGE_GEMINI_STRENGTH = 0.25
SDXL_ZIMAGE_UNKNOWN_STRENGTH = SDXL_ZIMAGE_GEMINI_STRENGTH


# sdxl-zimage picks its strength from the VENDOR (unlike qwen-zimage, which derives it
# from image area). An unlisted or unknown vendor falls back to the Gemini value.
_SDXL_ZIMAGE_STRENGTH_BY_VENDOR: dict[str, float] = {
    "openai": SDXL_ZIMAGE_OPENAI_STRENGTH,
    "google": SDXL_ZIMAGE_GEMINI_STRENGTH,
}
_ALIASES = {
    "qwen_zimage": QWEN_ZIMAGE_PROFILE,
    "sdxl_zimage": SDXL_ZIMAGE_PROFILE,
}


def normalize_profile(profile: str) -> str:
    """Normalize spelling and resolve the underscore spellings."""
    value = profile.strip().casefold()
    return _ALIASES.get(value, value)


def profile_supports_device(profile: str, device: str) -> bool:
    """Whether this profile's global stage can load on this device."""
    return device.casefold() in PROFILE_DEVICES.get(normalize_profile(profile), ())


def profiles_for_device(device: str) -> tuple[str, ...]:
    """Every profile this device can run, in the order they are preferred."""
    return tuple(profile for profile in PROFILE_CHOICES if profile_supports_device(profile, device))


def default_profile_for_device(device: str) -> str | None:
    """The profile chosen when the caller expressed no preference.

    CUDA keeps ``qwen-zimage``: the default must not change for the platform the
    profiles were certified on. MPS gets the only profile it can run, which is why
    the CLI's ``--pipeline`` default is "unset" rather than a literal -- a literal
    default is indistinguishable from a user who typed it, and the two deserve
    different answers (auto-select versus an error naming the reason).
    """
    candidates = profiles_for_device(device)
    if not candidates:
        return None
    if DEFAULT_PROFILE in candidates:
        return DEFAULT_PROFILE
    return candidates[0]


def face_stage_runs_on(device: str) -> bool:
    """Whether a masked face-repair stage can execute on this device."""
    return device.casefold() in FACE_STAGE_DEVICES


def face_stage_uses_zimage(device: str) -> bool:
    """Whether that stage is the Z-Image one, or the SDXL crops that stand in for it."""
    return device.casefold() in ZIMAGE_FACE_DEVICES


def sdxl_face_strength(strength: float) -> float:
    """Clamp a face strength to what the fp16 SDXL crop path can actually sample.

    Not a quality knob: below the floor the tail of the schedule stops producing an
    image at all. See ``SDXL_FACE_STRENGTH_FLOOR``.
    """
    return max(float(strength), SDXL_FACE_STRENGTH_FLOOR)


def required_modules(device: str) -> tuple[str, ...]:
    """The import names a real removal run needs on this device."""
    if face_stage_uses_zimage(device):
        return BASE_REMOVAL_MODULES + FACE_STAGE_MODULES
    return BASE_REMOVAL_MODULES


def install_extra_for_device(device: str) -> str:
    """The shell-quoted extra that makes a removal run work on this device."""
    return INVISIBLE_EXTRA if face_stage_uses_zimage(device) else INVISIBLE_EXTRA_MPS


@dataclass(frozen=True)
class ProfilePlan:
    """What a removal run will actually do on the resolved device."""

    profile: str
    device: str
    face_stage: bool
    # Set when the plan differs from what the caller would assume: an auto-selected
    # profile, or a stage that this device cannot run. Printed by the CLI, logged by
    # the remover. None means "exactly what was asked for".
    note: str | None = None


def plan_profile(requested: str | None, device: str) -> ProfilePlan:
    """Resolve profile, device support, and face-stage availability in one place.

    ``requested`` is None when the caller expressed no preference. Raises ValueError
    with an actionable message when the pair cannot run; the caller is expected to
    surface it verbatim, so it names the device, the reason, and the way forward.
    """
    device = device.casefold()
    runnable = profiles_for_device(device)
    if not runnable:
        raise ValueError(
            f"Invisible-watermark removal needs a GPU, so '{device}' cannot run it. "
            "Supported: CUDA (NVIDIA) and MPS (Apple Silicon). Visible-mark removal, "
            "metadata stripping and every identify command still run on CPU."
        )

    note: str | None = None
    if requested is None:
        # Total on a non-empty ``runnable``, which the guard above established.
        profile = default_profile_for_device(device) or runnable[0]
        if profile != DEFAULT_PROFILE:
            note = f"{DEFAULT_PROFILE} is CUDA-only, so {profile} was selected for {device}."
    else:
        profile = normalize_profile(requested)
        if profile not in PROFILE_CHOICES:
            raise ValueError(f"Unsupported pipeline '{requested}'. Use one of: {', '.join(PROFILE_CHOICES)}.")
        if not profile_supports_device(profile, device):
            raise ValueError(
                f"The {profile} profile cannot run on {device}: its Qwen-Image and Z-Image "
                "stacks stream float8 weights, a tensor type Metal does not implement. "
                f"On {device}, use --pipeline {', '.join(runnable)}."
            )

    face_stage = face_stage_runs_on(device)
    if face_stage and not face_stage_uses_zimage(device):
        face_note = (
            "The Z-Image face repair is CUDA-only (float8 storage), so masked faces are "
            "regenerated by the SDXL stage already loaded for the global pass."
        )
        note = f"{note} {face_note}" if note else face_note
    elif not face_stage:
        face_note = "No face-repair stage runs on this device; the global stage regenerates faces alone."
        note = f"{note} {face_note}" if note else face_note
    return ProfilePlan(profile=profile, device=device, face_stage=face_stage, note=note)


def resolve_seed(seed: int | None) -> int:
    """Keep both profiles reproducible by default."""
    return PROFILE_SEED if seed is None else seed


def resolve_adaptive_polish(adaptive_polish: bool | None, pipeline: str) -> bool:
    """Return an explicit polish choice, or the profile's calibrated default."""
    if adaptive_polish is not None:
        return adaptive_polish
    return PROFILE_ADAPTIVE_POLISH.get(normalize_profile(pipeline), True)


def strength_default_help() -> str:
    """Describe the live default policy without duplicating its values."""
    return (
        "profile-adaptive (qwen-zimage uses resolution-adaptive denoise; sdxl-zimage "
        f"uses OpenAI {SDXL_ZIMAGE_OPENAI_STRENGTH} / Google {SDXL_ZIMAGE_GEMINI_STRENGTH} / "
        f"unknown {SDXL_ZIMAGE_UNKNOWN_STRENGTH}, from the C2PA issuer)"
    )


def resolve_strength(
    strength: float | None,
    vendor: str | None = None,
    pipeline: str | None = None,
    *,
    size: tuple[int, int] | None = None,
) -> float:
    """Resolve a user override or the calibrated policy for a profile and vendor.

    Total by design. qwen-zimage picks its strength from image area rather than from
    the vendor, so it needs ``size``; returning ``None`` for it instead would push that
    branch onto every caller and move one of the two strength policies outside this
    module. ``size`` is required for qwen-zimage without an explicit strength.
    """
    if strength is not None:
        return strength
    if normalize_profile(pipeline or "") == SDXL_ZIMAGE_PROFILE:
        return _SDXL_ZIMAGE_STRENGTH_BY_VENDOR.get((vendor or "").casefold(), SDXL_ZIMAGE_UNKNOWN_STRENGTH)
    if size is None:
        raise ValueError("qwen-zimage resolves strength from image area, so size is required")
    from pagedmark._internal.qwen_zimage_pipeline import resolution_adaptive_denoise

    return resolution_adaptive_denoise(*size)


def vendor_for_strength(image_path: Path) -> Literal["openai", "google"] | None:
    """Select the strength cohort using the input's SynthID provenance evidence."""
    try:
        from pagedmark.metadata import synthid_source

        evidence = (synthid_source(image_path) or "").casefold()
    except Exception:
        return None
    if "google" in evidence:
        return "google"
    if "openai" in evidence:
        return "openai"
    return None
